import { Suspense } from 'react';
import type { Metadata } from 'next';

import Loading from './loading';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="bg-slate-300">
            <div className="container m-auto">
                <div className="flex min-h-screen items-center justify-center">
                    <div className="w-full max-w-md px-4">
                        <Suspense fallback={<Loading />}>{children}</Suspense>
                    </div>
                </div>
            </div>
        </div>
    );
}
